package automation.lang.editor;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Klasse zur Anzeige der Hilfe
 * @author Johannes
 */
public class Help extends javax.swing.JFrame {

    /** Creates new form Help */
    public Help() {
        initComponents();
        try {
            textpane.setPage(getClass().getResource("/automation/lang/editor/resources/docs/hilfe.html"));
            textpane2.setPage(getClass().getResource("/automation/lang/editor/resources/docs/editorbedienung.html"));
        } catch (IOException ex) {
            Logger.getLogger(Help.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        scroll_pane = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpane2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hilfe");
        setAlwaysOnTop(true);

        scroll_pane.setAutoscrolls(true);
        scroll_pane.setInheritsPopupMenu(true);

        textpane.setContentType("text/html");
        textpane.setEditable(false);
        textpane.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \rComing soon... For questions ask the author...\n    </p>\r\n  </body>\r\n</html>\r\n");
        scroll_pane.setViewportView(textpane);

        tabbedpane.addTab("Hilfe", scroll_pane);

        textpane2.setEditable(false);
        jScrollPane1.setViewportView(textpane2);

        tabbedpane.addTab("Editorbedienung", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scroll_pane;
    private javax.swing.JTabbedPane tabbedpane;
    private javax.swing.JTextPane textpane;
    private javax.swing.JTextPane textpane2;
    // End of variables declaration//GEN-END:variables

}
