package automatonlang.editor;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Klasse zur Anzeige der Hilfe
 * @author Johannes
 */
public class Help extends javax.swing.JFrame {

    /** Creates new form Help */
    public Help() {
        initComponents();
        try {
           String app = getLocale().getLanguage() == "de" ? "_de" : "_en";
            textpane.setPage(getClass().getResource("/automatonlang/editor/resources/docs/hilfe" + app + ".html"));
            textpane2.setPage(getClass().getResource("/automatonlang/editor/resources/docs/editorbedienung" + app + ".html"));
            textpane3.setPage(getClass().getResource("/automatonlang/editor/resources/docs/beispiele" + app + ".html"));
            textpane4.setPage(getClass().getResource("/automatonlang/editor/resources/docs/copyright" + app + ".html"));
            textpane5.setPage(getClass().getResource("/automatonlang/editor/resources/docs/release_notes" + app + ".html"));
        } catch (IOException ex) {
            Logger.getLogger(Help.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        scroll_pane = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpane2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textpane3 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textpane4 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        textpane5 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("automatonlang/editor/resources/localizations/localization"); // NOI18N
        setTitle(bundle.getString("HILFE")); // NOI18N
        setAlwaysOnTop(true);

        scroll_pane.setAutoscrolls(true);
        scroll_pane.setInheritsPopupMenu(true);

        textpane.setContentType("text/html");
        textpane.setEditable(false);
        textpane.setText("\n");
        scroll_pane.setViewportView(textpane);

        tabbedpane.addTab("Hilfe", scroll_pane);

        textpane2.setEditable(false);
        jScrollPane1.setViewportView(textpane2);

        tabbedpane.addTab(bundle.getString("EDITORBEDIENUNG"), jScrollPane1); // NOI18N

        textpane3.setEditable(false);
        jScrollPane2.setViewportView(textpane3);

        tabbedpane.addTab(bundle.getString("BEISPIELE"), jScrollPane2); // NOI18N

        textpane4.setEditable(false);
        jScrollPane3.setViewportView(textpane4);

        tabbedpane.addTab(bundle.getString("COPYRIGHT"), jScrollPane3); // NOI18N

        textpane5.setEditable(false);
        jScrollPane4.setViewportView(textpane5);

        tabbedpane.addTab(bundle.getString("RELEASE NOTES"), jScrollPane4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane scroll_pane;
    private javax.swing.JTabbedPane tabbedpane;
    private javax.swing.JTextPane textpane;
    private javax.swing.JTextPane textpane2;
    private javax.swing.JTextPane textpane3;
    private javax.swing.JTextPane textpane4;
    private javax.swing.JTextPane textpane5;
    // End of variables declaration//GEN-END:variables

}
